// <auto-generated />
namespace NewsWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class registererror : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(registererror));
        
        string IMigrationMetadata.Id
        {
            get { return "202106030149324_registererror"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
